### ISSUE TITLE
Option to use or not the menu (an other things)

### ISSUE THREAD

**Issue by adolphenom** [omphalosskeptic/mnml-ghost-theme#25]
Hi!

I like the theme a lot, but I don't like the menu. I still don't know how to make things in Ghost's themes, so I'll ask here: is it possible to add an option to always show the menu instead of the button to open and close it?

Of course I know it's possible modifying the theme, but I'm sure there's people who likes it.

Thank you in advance!

**Comment by adolphenom** [comment]
Oh, Thank you! :)

I don't like the menu because I like static stuff, but I'm not saying the menu is ugly or something like that. It's just a personal thing :)

On the other side, yes, it answers my question. I tried to download but it has password and I don't know what it is.

I'll give a try as soon as possible.

Thank you :) !

**Comment by omphalosskeptic** [comment]
@adolphenom, sorry about that — when I uploaded, I thought the password was for modifying the files, not downloading them. The password is `testing`.

**Comment by adolphenom** [comment]
So... I tried today. Even I don't like non-justify text, in this case, it's so cool. Afther that, I saw some stuff.

* The column is not perfectly centered. That's for the vertical bar, and it can be hidden but it's not intuitive for the user.
* The logo at the top-left, could be another thing? Or maybe can it be at the title instead of there? I mean, instead of having such logo up there, change for the classical link at the title.
* Instead of having the first 2 or 3 phrases of the text, could it be changed for the SEO text? 

I don't know if I have to suggest something more. If you don't understand something (because of my english), please let me know.

Thank you for being open to suggestions!

**Comment by omphalosskeptic** [comment]
Thanks!  Look good on your blog. I have a lot planned for the theme, but I’m pretty busy this weekend.

1. I’m not sure I entirely understand which column isn’t centered; are you talking about the menu bar?
2. Yes, if I understant correctly. Meaning a little home link? On the other hand, I think it looks good on year blog (I didn’t know the logo still worked!). Also, it’s slightly off-center from the padding on `.main-nav`,  which I’ll see what I can do about.
3. It’d be great to switch the excerpts for the meta description/SEO text; I took a quick look at the Ghost theme docs, and I don’t know if it’s possible at this point, but I’ll look into it again and get back to you

Your English is a lot better than my Spanish ;) If you can give me more details about points 1 & 2, I’ll se what I can do and get back to you after the weekend. Thanks for trying it out!

**Comment by adolphenom** [comment]
Sure :)

1. When you drop the theme and set up in Ghost, the theme has 1 column in the feed. If the vertical scroll bar is active, the column is moved to the left a few pixels. That's what I mean with centered. But, for the user, it's better to have that bar instead of being hidden.
2. Well, I mean, when you do a website, you put a link in <a> tag, right? So it's the same for the title of the blog. Instead of having the logo to get on the feed, you click on the title. I don't know. I'm thinking now and maybe it's not good having the profile's photo as blog's logo. The second point doesn't matter, it was an old idea.

Another thing I saw. All the fonts in the theme are not at the CSS. When I enter to my blog, font changes to what I have in my Chrome's settings. It'll be a good idea to have all the fonts in the CSS, so the appearance doesn't change a lot.

**Comment by omphalosskeptic** [comment]
@adolphenom  The bottom screenshot is correct: the theme uses [hanging punctuation](http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2), which is a typographically sound practice.

**Regarding point 1 and the fonts issues: could you provide screeshots so I can have an idea of what’s going on visually?** The theme should use Source Sans Pro, Source Serif Pro, and Alegreya. The webfonts are provided by Brick.im, and the font-face code is near the end of defer.css. The little screenshot you showed looks right to me. Are your chrome settings default, or do you have some special styling?

Your blog seems to be using the right fonts when I visit it…

**Comment by adolphenom** [comment]
I didn't know about the hanging punctuation. I learnt something new today :)!

I think I was wrong about fonts. I thought it was me, but it's everything correct, I looked at the code.

**Comment by omphalosskeptic** [comment]
I’ll close this issue now that you have the modified menu files … when Ghost supports proper theme customization I’ll be able to add more configuration options, like the option to have the Menu showing by default.
