### ISSUE TITLE
Add next / previous post links at the bottom of a post

### ISSUE THREAD

**Issue by vickychijwani** [omphalosskeptic/mnml-ghost-theme#26]
I think this is a useful feature to have because it has the potential to increase reader engagement levels on my blog.

**Comment by omphalosskeptic** [comment]
@vickychijwani Good idea! I should have more time in a few days, and I’ll look into ways of doing this.

I’ll leave this issue open until then.

**Comment by vickychijwani** [comment]
Not sure if you know about this already, but you might want to wait some time for TryGhost/Ghost#4262 to get resolved. That'll make your work a lot easier I suspect :)

**Comment by vickychijwani** [comment]
Actually, TryGhost/Ghost#4799 is more appropriate here.

**Comment by omphalosskeptic** [comment]
Ah. Looks like a helper is on the way. I’ll put this issue on hold until then…
